// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdlqouqphojcrcmyeuak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkbHFvdXFwaG9qY3JjbXlldWFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MDg0NzQsImV4cCI6MjA3MzQ4NDQ3NH0.Uo03xEWFZ-NYQxZqD_10JJlIidHG40tYzsdQfrKwwIQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});